import type { Dictionary } from "./interface.ts";

export const recipeIndex: Dictionary<string> = {
    "bread-1": "quick-flatbread",
    "bread-2": "focaccia",
    "bread-3": "pizza-dough",
    "dimsum-1": "shrimp-lotus-root-dim-sum",
    "pastry-1": "chinese-puff-pastry",
    "pastry-2": "char-siu-so",
    "pastry-3": "rainbow-flaky-mooncake",
    "pastry-4": "egg-tart",
    "cookie-1": "citrus-shortbread",
    "cookie-2": "gingersnap",
    "cookie-3": "hamster-sugar-cookies",
    "cookie-4": "apple-filled-icebox-cookies",
    "cookie-5": "langue-de-chat",
    "filling-1": "bean-paste",
    "filling-2": "custard-moon-cakes",
    "filling-3": "chestnut-paste",
    "filling-4": "sweet-coconut-filling",
    "filling-5": "lemon-curd",
    "sauce-1": "roasted-veggie-pasta-sauce",
    "sauce-2": "teriyaki-sauce",
    "soup-1": "chicken-coconut-soup",
    "soup-2": "vegetable-soup",
    "meat-1": "saucy-pork",
    "meat-2": "soy-sauce-chicken-drumsticks",
    "meat-3": "spare-ribs-pumpkin",
    "meat-4": "hamburger",
    "meat-5": "baked-chicken",
    "dessert-1": "snow-skin-mooncake",
    "dessert-2": "apple-crumble",
    "dessert-3": "fruity-cake",
    "dessert-4": "walnut-soup",
    "dessert-5": "apple-muffin",
    "dessert-6": "coffee-jelly",
};